-- Stores periodically-generated narrative trend reports shown at the bottom
-- of the Trends page. Appended to (not upserted) so there's a history;
-- the page just reads the most recent row. Generated by
-- scripts/generate-trend-report.js, run daily after aggregate-trends.js.
create table public.trend_reports (
  id uuid primary key default gen_random_uuid(),
  generated_at timestamptz not null default now(),
  report_text text not null,
  model text not null
);

create index trend_reports_generated_at_idx on public.trend_reports (generated_at desc);
